# Generated by Django 5.2 on 2025-04-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palettes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palette',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='palette',
            unique_together={('name', 'colors')},
        ),
    ]
